package com.santosh;

import java.util.Date;

/**
 * This class is used as POJO for Expense
 * @author Santosh Pandey
 *
 */
public class Expense {
	
	/**
	 * ID for Expense
	 * Auto Generated by System
	 */
	Long expenseId=System.currentTimeMillis();
	
	/**
	 * ID of category
	 */
	Long categoryId;
	
	/**
	 * amount in float
	 */
	Float amount;
	
	/**
	 * Expense date
	 */
	Date date;
	
	/**
	 * remark of Expense
	 */
	String remark;
	
	
	public Long getExpenseId() {
		return expenseId;
	}
	public void setExpenseId(Long expenseId) {
		this.expenseId = expenseId;
	}
	public Long getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	public Float getAmount() {
		return amount;
	}
	public void setAmount(Float amount) {
		this.amount = amount;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public Expense(Long categoryId, Float amount, Date date, String remark) {
		super();
		this.categoryId = categoryId;
		this.amount = amount;
		this.date = date;
		this.remark = remark;
	}
	
	public Expense() {
		
	}
	
}
