package com.santosh.pem.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * This class is used as POJO for Expense
 * @author Santosh Pandey
 *
 */
public class Expense implements Serializable {
	
	/**
	 * ID for Expense
	 * Auto Generated by System
	 */
	private int expenseId;
	
	/**
	 * ID of category
	 */
	private int categoryId;
	
	/**
	 * amount in float
	 */
	private int amount;
	
	/**
	 * Expense date
	 */
	private Date date;
	
	/**
	 * remark of Expense
	 */
	private String remark;
	
	/**
	 * User Id
	 */
	private int userId;

	public int getExpenseId() {
		return expenseId;
	}

	public void setExpenseId(int expenseId) {
		this.expenseId = expenseId;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Expense(int expenseId, int categoryId, int amount, Date date, String remark, int userId) {
		super();
		this.expenseId = expenseId;
		this.categoryId = categoryId;
		this.amount = amount;
		this.date = date;
		this.remark = remark;
		this.userId = userId;
	}
	
	public Expense() {

	}


}
